version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: landing
    restart: unless-stopped
    networks:
      - vpn_net
    volumes:
      - ./html:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      # Modificar domain.com por dominio real
      # HTTP router (redirige a HTTPS)
      - "traefik.http.routers.landing.entrypoints=http"
      - "traefik.http.routers.landing.rule=Host(`domain.com`)"
      - "traefik.http.middlewares.landing-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.landing.middlewares=landing-https-redirect"

      # HTTPS router
      - "traefik.http.routers.landing-secure.entrypoints=https"
      - "traefik.http.routers.landing-secure.rule=Host(`domain.com`)"
      - "traefik.http.routers.landing-secure.tls=true"
      - "traefik.http.routers.landing-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.landing-secure.tls.domains[0].main=domain.com"

      # Puerto interno del contenedor (ajusta si es diferente)
      - "traefik.http.services.landing.loadbalancer.server.port=80"

networks:
  vpn_net:
    external: true
